services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: travelukraine-django:latest
    container_name: travelukraine-django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
