# Generated by Django 6.0.6 on 2026-06-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='ideal_days_for_rest',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
