# Generated by Django 6.0.6 on 2026-06-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0002_place_ideal_days_for_rest'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='best_season',
            field=models.CharField(choices=[('any', 'Будь-який сезон'), ('spring', 'Весна'), ('summer', 'Літо'), ('autumn', 'Осінь'), ('winter', 'Зима')], default='any', max_length=20),
        ),
    ]
