# Generated by Django 6.0.6 on 2026-06-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0003_place_best_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
