# Generated by Django 6.0.6 on 2026-07-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0005_remove_place_image_url_place_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
        migrations.AddField(
            model_name='place',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
